// frontend/local-media-gallery-frontend/src/components/folder-display.vue
<script setup>
import { useRouter } from 'vue-router'
import { encodeResourceSrc } from '../utils/utilities'

const router = useRouter()
// eslint-disable-next-line no-unused-vars
const props = defineProps({
  folders: Array,
  staticFileAddress: String
})

// if the folder name is too long (e.g. manga name), only display author name
const getFolderNameToDisplay = (string) => {
  return string.length >= 20 ? string.split('-')[0] : string
}
</script>

<!--  -->
<template>
  <div class="container-fluid">
    <div class="row mt-0 mb-4 gx-1 gy-4">
      <div v-for="folder in folders" :key="folder.name" class="col-6 col-xl-2 text-center">
        <button
          @click="router.push(folder.src)"
          type="button"
          class="folderBtn btn btn-primary text-center p-0"
        >
          <div id="folderTitle" class="py-1">{{ getFolderNameToDisplay(folder.name) }}</div>
          <img
            v-if="'thumbnail' in folder"
            :width="folder.thumbnail.width"
            :height="folder.thumbnail.height"
            alt=""
            loading="lazy"
            class="mt-1 pb-1 img-fluid"
            :src="encodeResourceSrc(staticFileAddress, folder.thumbnail.src)"
          />
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped>
button.folderBtn {
  width: 100%;
}
div#folderTitle {
  word-wrap: break-word;
}
</style>

// web/app/components/FolderDisplay.tsx
import Link from "next/link";
import { encodeResourceSrc } from "@/app/scripts/utils";

interface FolderDisplayProps {
	folders: Folder[];
	hostAddress: string;
}

export default function FolderDisplay({
	folders,
	hostAddress,
}: FolderDisplayProps) {
	return (
		<div className="container-fluid px-0">
			<div className="row mb-4 gx-1 gy-4">
				{folders.map((folder) => (
					<div
						key={folder.name}
						className="col-6 col-sm-4 col-md-3 col-xl-2 text-center"
					>
						<Link
							href={folder.url}
							type="button"
							className="btn-width btn btn-primary p-0"
						>
							<div className="py-1 truncate mx-auto">
								{folder.name}
							</div>
							{folder.thumbnail && (
								<img
									width={folder.thumbnail.image.width}
									height={folder.thumbnail.image.height}
									loading="lazy"
									className="rounded-bottom img-fluid"
									src={encodeResourceSrc(
										hostAddress,
										folder.thumbnail.image.url
									)}
								/>
							)}
						</Link>
					</div>
				))}
			</div>
		</div>
	);
}
