// web/src/components/NavBar.vue
<script setup lang="ts">
import { useRoute, useRouter } from 'vue-router'

const route = useRoute()
const router = useRouter()

const props = defineProps<{
  navBarTitle: string
}>()

const goBackToUpperPath = () => {
  const pathSegments = props.navBarTitle.split('/').filter(Boolean)
  pathSegments.pop()
  const newPath = `/${pathSegments.join('/')}`

  router.push(newPath)
}
</script>

<template>
  <div class="container-fluid my-3">
    <div class="h2 mt-1 d-flex">
      <button
        v-if="route.path !== '/'"
        type="button"
        class="btn btn-secondary d-inline me-2"
        @click="goBackToUpperPath"
      >
        <i className="bi bi-chevron-left me-1"></i>
      </button>
      <span className="align-self-center"> {{ navBarTitle || 'Loading...' }} </span>
      <!-- <button
        v-if="route.name === 'Favorite Viewer'"
        type="button"
        class="btn btn-secondary d-inline ms-auto"
        @click="$emit('onClickSortFavBtn')"
      >
        Sort/Refresh Fav
      </button> -->
    </div>
  </div>
</template>

<style scoped></style>

// web/app/components/Navbar.tsx
"use client";

import { useRouter } from "next/navigation";

interface NavBarProps {
	navBarTitle: string;
}

export default function Navbar({ navBarTitle }: NavBarProps) {
	const router = useRouter();

	function goBackToUpperPath() {
		const pathSegments = navBarTitle.split("/").filter(Boolean);
		pathSegments.pop();
		const newPath = `/${pathSegments.join("/")}`;

		router.push(newPath);
	}

	return (
		<div className="container-fluid my-3">
			<div className="h2 mt-1 d-flex">
				{navBarTitle !== "/" && (
					<button
						type="button"
						className="btn btn-secondary d-inline me-2"
						onClick={goBackToUpperPath}
					>
						<i className="bi bi-chevron-left me-1"></i>
					</button>
				)}
				<span className="align-self-center">
					{navBarTitle || "Loading..."}
				</span>
			</div>
		</div>
	);
}
