// web/app/components/FolderDisplay.tsx
import Link from "next/link";
import { encodeResourceSrc } from "@/app/scripts/utils";

interface FolderDisplayProps {
	folders: Folder[];
	hostAddress: string;
}

export default function FolderDisplay({
	folders,
	hostAddress,
}: FolderDisplayProps) {
	return (
		<div className="container-fluid px-0">
			<div className="row mb-4 gx-1 gy-4">
				{folders.map((folder) => (
					<div
						key={folder.name}
						className="col-6 col-sm-4 col-md-3 col-xl-2 text-center"
					>
						<Link
							href={folder.url}
							type="button"
							className="btn-width btn btn-primary p-0"
						>
							<div className="py-1 truncate mx-auto">
								{folder.name}
							</div>
							{folder.thumbnail && (
								<img
									width={folder.thumbnail.image.width}
									height={folder.thumbnail.image.height}
									loading="lazy"
									className="rounded-bottom img-fluid"
									src={encodeResourceSrc(
										hostAddress,
										folder.thumbnail.image.url
									)}
								/>
							)}
						</Link>
					</div>
				))}
			</div>
		</div>
	);
}

// web/src/components/folder-display.vue
<script setup lang="ts">
import { useRouter } from 'vue-router'
import { encodeResourceSrc } from '@/utils/utils'

const router = useRouter()
// eslint-disable-next-line no-unused-vars
const props = defineProps({
  folders: Array,
  staticFileAddress: String,
})
</script>

<!--  -->
<template>
  <div class="container-fluid">
    <div class="row mt-0 mb-4 gx-1 gy-4">
      <div v-for="folder in folders" :key="folder.name" class="col-6 col-xl-2 text-center">
        <button
          @click="router.push(folder.url)"
          type="button"
          class="btn-width btn btn-primary p-0"
        >
          <div class="py-1 truncate mx-auto">
            {{ folder.name }}
          </div>
          <img
            v-if="folder.thumbnail"
            :width="folder.thumbnail.width"
            :height="folder.thumbnail.height"
            alt=""
            loading="lazy"
            class="rounded-bottom img-fluid"
            :src="encodeResourceSrc(staticFileAddress, folder.thumbnail.image.url)"
          />
        </button>
      </div>
    </div>
  </div>
</template>

<style scoped></style>
